import { Incident } from '../types/incidents';
import { Mission } from '../types/missions';
import { ResourceItem } from '../types/resources';
import { Vehicle } from '../types/vehicles';
import { PersonnelTeam } from '../types/personnel';
import { Hospital } from '../types/hospitals';
import { Shelter } from '../types/shelters';

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'inc-1',
    code: 'INC-2026-0891',
    type: 'Flood',
    title: 'Sector 7 Coastal Surge & Levee Breach',
    location: 'Marina Bay Basin, Sector 7',
    sector: 'Sector 7 (Coastal)',
    coordinates: [-118.4912, 34.0194],
    priority: 'P1 Critical',
    status: 'In Progress',
    affectedPopulation: 14200,
    reportedAt: new Date(Date.now() - 3600000 * 2.5).toISOString(),
    assignedTeamId: 'team-1',
    assignedTeamName: 'Tactical Water Rescue Squad 4',
    assignedVehicleId: 'veh-1',
    assignedVehicleName: 'Rescue Airboat Alpha-1',
    description: 'Levee breach following Category 4 tidal surge. Water height +3.4m over normal datum. Mandatory evacuation protocol active.',
    history: [
      { timestamp: new Date(Date.now() - 3600000 * 2.5).toISOString(), action: 'Incident Logged via Telemetry Sensor 4B', operator: 'Automated Alert' },
      { timestamp: new Date(Date.now() - 3600000 * 2.0).toISOString(), action: 'Priority Elevated to P1 Critical', operator: 'Commander Alex Vance' },
      { timestamp: new Date(Date.now() - 3600000 * 1.2).toISOString(), action: 'Dispatched Tactical Squad 4 and Rescue Airboat Alpha-1', operator: 'Officer Marcus Brody' },
    ],
  },
  {
    id: 'inc-2',
    code: 'INC-2026-0892',
    type: 'Wildfire',
    title: 'Ridge Line Forest Blaze & Ember Flight',
    location: 'East Ridge Wilderness, Sector 3',
    sector: 'Sector 3 (North Ridge)',
    coordinates: [-118.3500, 34.1200],
    priority: 'P1 Critical',
    status: 'In Progress',
    affectedPopulation: 8500,
    reportedAt: new Date(Date.now() - 3600000 * 5.1).toISOString(),
    assignedTeamId: 'team-2',
    assignedTeamName: 'Wildland Combat Alpha',
    assignedVehicleId: 'veh-2',
    assignedVehicleName: 'Air Tanker Heavy Drop 9',
    description: 'High wind gusts pushing 1,200ha wildfire perimeter eastward toward residential grid C. Aerial water drops active.',
    history: [
      { timestamp: new Date(Date.now() - 3600000 * 5.1).toISOString(), action: 'Thermal Satellite Hotspot Detected', operator: 'AI Risk Monitor' },
      { timestamp: new Date(Date.now() - 3600000 * 4.0).toISOString(), action: 'Air Tanker 9 Deployed for Suppression', operator: 'Commander Alex Vance' },
    ],
  },
  {
    id: 'inc-3',
    code: 'INC-2026-0893',
    type: 'Earthquake',
    title: 'Fault Line Mag 5.8 Tremor & Structural Breach',
    location: 'Metro Downtown Commercial District',
    sector: 'Sector 1 (Central Grid)',
    coordinates: [-118.2500, 34.0450],
    priority: 'P2 High',
    status: 'Dispatched',
    affectedPopulation: 32000,
    reportedAt: new Date(Date.now() - 3600000 * 1.1).toISOString(),
    assignedTeamId: 'team-3',
    assignedTeamName: 'USAR Urban Collapse Unit 1',
    assignedVehicleId: 'veh-3',
    assignedVehicleName: 'Heavy Rescue Engine 4',
    description: 'Shallow 12km epicenter. Structural integrity checks underway for overpasses and high-rise structures.',
    history: [
      { timestamp: new Date(Date.now() - 3600000 * 1.1).toISOString(), action: 'Seismograph Threshold Triggered', operator: 'Seismic Network' },
    ],
  },
  {
    id: 'inc-4',
    code: 'INC-2026-0894',
    type: 'Hazmat Spill',
    title: 'Industrial Chemical Tanker Rupture',
    location: 'Harbor Rail Yard, Sector 5',
    sector: 'Sector 5 (Industrial)',
    coordinates: [-118.2900, 33.9800],
    priority: 'P2 High',
    status: 'New',
    affectedPopulation: 2100,
    reportedAt: new Date(Date.now() - 3600000 * 0.4).toISOString(),
    description: 'Corrosive vapor plume detected. 800-meter exclusion perimeter established.',
    history: [],
  },
  {
    id: 'inc-5',
    code: 'INC-2026-0895',
    type: 'Structural Collapse',
    title: 'Bridge Overpass Support Failure',
    location: 'Highway 10 Interchange, Sector 2',
    sector: 'Sector 2 (West)',
    coordinates: [-118.4000, 34.0300],
    priority: 'P3 Moderate',
    status: 'Resolved',
    affectedPopulation: 450,
    reportedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    description: 'Debris cleared, traffic diverted safely.',
    history: [],
  },
];

export const MOCK_MISSIONS: Mission[] = [
  {
    id: 'msn-101',
    code: 'MSN-TACTICAL-44',
    title: 'Operation Tidal Shield Evac',
    incidentCode: 'INC-2026-0891',
    priority: 'CRITICAL',
    status: 'ENGAGED',
    commanderName: 'Captain Sarah Jenkins',
    commanderRole: 'Rescue Team Leader',
    membersCount: 24,
    members: ['Capt. S. Jenkins', 'Lt. M. Torres', 'Sgt. R. Chen', 'Spec. J. Miller', 'Tech. K. Davis'],
    progressPercent: 68,
    sector: 'Sector 7 (Coastal)',
    startedAt: '08:00 UTC',
    estimatedCompletion: '14:30 UTC',
    notes: '240 civilians evacuated via airboats. Medical triage station active at Pier 4.',
    reportsCount: 5,
  },
  {
    id: 'msn-102',
    code: 'MSN-FIRE-09',
    title: 'Ridge Line Perimeter Defense',
    incidentCode: 'INC-2026-0892',
    priority: 'CRITICAL',
    status: 'DEPLOYED',
    commanderName: 'Chief Robert Vance',
    commanderRole: 'Fire Commander',
    membersCount: 42,
    members: ['Chief R. Vance', 'Capt. D. Miller', 'Lt. H. Smith'],
    progressPercent: 45,
    sector: 'Sector 3 (North Ridge)',
    startedAt: '05:30 UTC',
    estimatedCompletion: '18:00 UTC',
    notes: 'Firebreaks cut along Highway 39. Retardant drops scheduled.',
    reportsCount: 8,
  },
  {
    id: 'msn-103',
    code: 'MSN-USAR-01',
    title: 'Metro Seismic Grid Assessment',
    incidentCode: 'INC-2026-0893',
    priority: 'HIGH',
    status: 'STAGING',
    commanderName: 'Lt. Marcus Brody',
    commanderRole: 'USAR Specialist',
    membersCount: 16,
    members: ['Lt. M. Brody', 'Insp. T. Wong'],
    progressPercent: 15,
    sector: 'Sector 1 (Central)',
    startedAt: '10:15 UTC',
    estimatedCompletion: '16:00 UTC',
    notes: 'Acoustic listening devices deployed near collapsed parking structure.',
    reportsCount: 2,
  },
];

export const MOCK_RESOURCES: ResourceItem[] = [
  {
    id: 'res-1',
    code: 'RES-RAT-900',
    name: 'MRE Emergency Rations (Boxes)',
    category: 'Food & Rations',
    currentStock: 14500,
    minThreshold: 3000,
    unit: 'Boxes',
    storageHub: 'Central Logistics Depot A',
    status: 'OPTIMAL',
    lastReplenished: '2026-09-12',
  },
  {
    id: 'res-2',
    code: 'RES-WTR-500',
    name: 'Potable Water Drums (200L)',
    category: 'Water',
    currentStock: 420,
    minThreshold: 1000,
    unit: 'Drums',
    storageHub: 'Central Logistics Depot A',
    status: 'LOW STOCK',
    lastReplenished: '2026-09-10',
  },
  {
    id: 'res-3',
    code: 'RES-MED-101',
    name: 'Trauma First-Aid Kits',
    category: 'Medical Kits',
    currentStock: 85,
    minThreshold: 200,
    unit: 'Kits',
    storageHub: 'Harbor Emergency Hub B',
    status: 'CRITICAL EMPTY',
    lastReplenished: '2026-09-08',
  },
  {
    id: 'res-4',
    code: 'RES-FUL-90',
    name: 'Diesel Fuel (Litres)',
    category: 'Fuel',
    currentStock: 28400,
    minThreshold: 5000,
    unit: 'Litres',
    storageHub: 'Command Fuel Depot',
    status: 'OPTIMAL',
    lastReplenished: '2026-09-13',
  },
  {
    id: 'res-5',
    code: 'RES-GEN-50',
    name: 'Heavy Industrial Generators (100kW)',
    category: 'Generators',
    currentStock: 34,
    minThreshold: 10,
    unit: 'Units',
    storageHub: 'Sector 3 Staging Post',
    status: 'OPTIMAL',
    lastReplenished: '2026-09-11',
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    code: 'V-AMB-01',
    name: 'Rescue Ambulance Unit 101',
    type: 'Ambulance',
    status: 'ON MISSION',
    driverName: 'Paramedic John Doe',
    fuelPercent: 88,
    assignedStation: 'Metro Central Trauma Station',
    currentSector: 'Sector 7 (Coastal)',
    maintenanceDue: '2026-10-15',
  },
  {
    id: 'veh-2',
    code: 'V-FIRE-09',
    name: 'Wildland Fire Engine 9',
    type: 'Fire Truck',
    status: 'ON MISSION',
    driverName: 'Driver Sam Wilson',
    fuelPercent: 62,
    assignedStation: 'North Ridge Fire Station 4',
    currentSector: 'Sector 3 (North Ridge)',
    maintenanceDue: '2026-11-01',
  },
  {
    id: 'veh-3',
    code: 'V-HELI-02',
    name: 'Air Rescue Chopper Alpha',
    type: 'Helicopter',
    status: 'AVAILABLE',
    driverName: 'Pilot Sarah Connor',
    fuelPercent: 100,
    assignedStation: 'HQ Helipad Airbase',
    currentSector: 'Sector 1 (Central)',
    maintenanceDue: '2026-09-28',
  },
  {
    id: 'veh-4',
    code: 'V-[#00D4FF]-DRONE',
    name: 'Thermal Scout Drone Fleet 4',
    type: 'Drone Unit',
    status: 'ON MISSION',
    driverName: 'Tech Operator K. Davis',
    fuelPercent: 74,
    assignedStation: 'Mobile Command Rig 1',
    currentSector: 'Sector 7 (Coastal)',
    maintenanceDue: '2026-09-20',
  },
  {
    id: 'veh-5',
    code: 'V-BOAT-03',
    name: 'Coastal Inflatable Boat 3',
    type: 'Rescue Boat',
    status: 'AVAILABLE',
    driverName: 'Coxswain R. Chen',
    fuelPercent: 95,
    assignedStation: 'Marina Marine Station',
    currentSector: 'Sector 7 (Coastal)',
    maintenanceDue: '2026-12-10',
  },
];

export const MOCK_PERSONNEL: PersonnelTeam[] = [
  {
    id: 'team-1',
    code: 'SQD-RESCUE-4',
    name: 'Tactical Water Rescue Squad 4',
    category: 'Tactical Rescue',
    leaderName: 'Capt. Sarah Jenkins',
    memberCount: 24,
    specialization: 'Flood Inundation & Swift Water Extraction',
    currentMission: 'Operation Tidal Shield Evac',
    status: 'ON MISSION',
    baseStation: 'Marina Marine Station',
  },
  {
    id: 'team-2',
    code: 'SQD-FIRE-ALPHA',
    name: 'Wildland Combat Alpha',
    category: 'Fire Combat',
    leaderName: 'Chief Robert Vance',
    memberCount: 42,
    specialization: 'Wildland Containment & Aerial Drops',
    currentMission: 'Ridge Line Perimeter Defense',
    status: 'ON MISSION',
    baseStation: 'North Ridge Fire Station 4',
  },
  {
    id: 'team-3',
    code: 'SQD-USAR-01',
    name: 'USAR Urban Collapse Unit 1',
    category: 'Tactical Rescue',
    leaderName: 'Lt. Marcus Brody',
    memberCount: 16,
    specialization: 'Confined Space & Heavy Concrete Breaching',
    currentMission: 'Metro Seismic Grid Assessment',
    status: 'ON DUTY - STAGING',
    baseStation: 'Metro Central Station',
  },
  {
    id: 'team-4',
    code: 'SQD-MED-TRAUMA',
    name: 'Mobile Surgical Unit Bravo',
    category: 'Medical Trauma',
    leaderName: 'Dr. Emily Carter',
    memberCount: 12,
    specialization: 'Mass Casualty Triage & Field Surgery',
    status: 'ON DUTY - STAGING',
    baseStation: 'St. Jude General Hospital',
  },
];

export const MOCK_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'St. Jude General Trauma Hospital',
    location: '100 Medical Plaza, Sector 1',
    sector: 'Sector 1 (Central)',
    totalBeds: 500,
    occupiedBeds: 445,
    icuBedsTotal: 60,
    icuBedsOccupied: 58,
    doctorsOnDuty: 45,
    ambulancesStationed: 12,
    status: 'HIGH OCCUPANCY',
    phone: '+1 (555) 019-2831',
  },
  {
    id: 'hosp-2',
    name: 'Metro Coastal Emergency Medical Center',
    location: '450 Ocean Ave, Sector 7',
    sector: 'Sector 7 (Coastal)',
    totalBeds: 300,
    occupiedBeds: 298,
    icuBedsTotal: 35,
    icuBedsOccupied: 35,
    doctorsOnDuty: 28,
    ambulancesStationed: 6,
    status: 'DIVERSION ALERT',
    phone: '+1 (555) 019-8842',
  },
  {
    id: 'hosp-3',
    name: 'North Ridge Regional Hospital',
    location: '88 Mountain Rd, Sector 3',
    sector: 'Sector 3 (North Ridge)',
    totalBeds: 250,
    occupiedBeds: 140,
    icuBedsTotal: 25,
    icuBedsOccupied: 12,
    doctorsOnDuty: 20,
    ambulancesStationed: 8,
    status: 'NORMAL',
    phone: '+1 (555) 019-3391',
  },
];

export const MOCK_SHELTERS: Shelter[] = [
  {
    id: 'sh-1',
    name: 'Sector 7 Community Arena Shelter',
    location: '120 Sports Complex Dr, Sector 7',
    sector: 'Sector 7 (Coastal)',
    capacity: 2500,
    currentOccupancy: 2180,
    foodSupplyDays: 5,
    waterLitres: 12000,
    hasMedicalSupport: true,
    hasPowerGenerator: true,
    hasInternet: true,
    status: 'NEAR CAPACITY',
    contactPerson: 'Manager Arthur Pendelton',
  },
  {
    id: 'sh-2',
    name: 'High School Evacuation Hub West',
    location: '550 Academic Way, Sector 2',
    sector: 'Sector 2 (West)',
    capacity: 1200,
    currentOccupancy: 640,
    foodSupplyDays: 8,
    waterLitres: 18000,
    hasMedicalSupport: true,
    hasPowerGenerator: true,
    hasInternet: true,
    status: 'OPEN',
    contactPerson: 'Director Martha Stewart',
  },
  {
    id: 'sh-3',
    name: 'North Convention Center Shelter',
    location: '900 Civic Center Blvd, Sector 3',
    sector: 'Sector 3 (North Ridge)',
    capacity: 4000,
    currentOccupancy: 1200,
    foodSupplyDays: 14,
    waterLitres: 35000,
    hasMedicalSupport: true,
    hasPowerGenerator: true,
    hasInternet: true,
    status: 'OPEN',
    contactPerson: 'Officer Karen Brady',
  },
];
